NOTE: To render these, use the PlantUML plugin.

@startuml
actor User
User->Login: login()
activate Login
Login--> User
deactivate Login
|||
User->>TradingMain: bookTrade(Asset)
Activate TradingMain
activate Market
TradingMain->>Market: bookTrade(Asset)
deactivate Market
deactivate TradingMain
|||
Market->>TradingMain
activate Market
activate TradingMain
|||
TradingMain->TradingMain: saveTradeDetails
activate TradingMain
deactivate Market
TradingMain -> TradeDAL ** : create
TradingMain->TradeDAL: saveTradeDetails
database DB
TradeDAL->DB: saveTradeDetails
DB-->TradeDAL
TradeDAL-->TradingMain
|||
deactivate TradingMain
deactivate TradingMain


@enduml


@startuml
TradingMain->TradeDAL: saveTradeDetails
|||
TradeDAL-->TradingMain
|||
|||
@enduml

@startuml
actor User
User->TradingMain: bookTrade
activate TradingMain
TradingMain -> TradeDAL ** : create
TradingMain->TradeDAL: saveTradeDetails
database DB
activate TradeDAL
TradeDAL->DB: saveTradeDetails
deactivate TradeDAL
deactivate TradingMain
@enduml

@startuml
TradingMain->>Market: bookTrade(Asset)
activate Market
Activate TradingMain
deactivate Market
deactivate TradingMain
|||
|||
|||
@enduml
